"""Adding remember hashes

Revision ID: 105c7160a2f9
Revises: 1c2afdd96fe1
Create Date: 2024-01-24 21:42:41.159476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '105c7160a2f9'
down_revision = '1c2afdd96fe1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('remembers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('remember_hash', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_remembers_user_id'), 'remembers', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_remembers_user_id'), table_name='remembers')
    op.drop_table('remembers')
    # ### end Alembic commands ###
