"""Adding account activation

Revision ID: 70644c00ed6d
Revises: 5ae8c88d0a43
Create Date: 2024-02-18 11:36:59.858670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70644c00ed6d'
down_revision = '5ae8c88d0a43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('activated', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('activation_hash', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('activation_sent_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'activation_sent_at')
    op.drop_column('users', 'activation_hash')
    op.drop_column('users', 'activated')
    # ### end Alembic commands ###
