"""Adding user roles

Revision ID: a13ea83f2b99
Revises: 105c7160a2f9
Create Date: 2024-01-29 21:29:10.230386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a13ea83f2b99'
down_revision = '105c7160a2f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role_id')
    # ### end Alembic commands ###
