"""Adding password reset

Revision ID: ff9dee73423b
Revises: 70644c00ed6d
Create Date: 2024-02-24 08:28:00.941134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff9dee73423b'
down_revision = '70644c00ed6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reset_hash', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('reset_sent_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'reset_sent_at')
    op.drop_column('users', 'reset_hash')
    # ### end Alembic commands ###
